javascript_compressor: "closure"

javascripts:
    general:
        - public/javascripts/jquery.js
        - public/javascripts/rails.js
        - public/javascripts/application.js
        - public/javascripts/isotope.js
        - public/javascripts/infinitescroll.js
        - public/javascripts/projects.js
        
        
        
    staff:
        - public/javascripts/jquery.js
        - public/javascripts/jquery.ui.js
        - public/javascripts/rails.js
        - public/javascripts/application.js
        - public/javascripts/tag_cloud_select.js
        - public/javascripts/photo_inputs.js
        - public/javascripts/photo_form.js
        
 
stylesheets:
    public:
        - public/stylesheets/screen.css
    print:
        - public/stylesheets/print.css
    staff:
         - public/stylesheets/staff/main.css
         - public/stylesheets/staff/general.css
         - public/stylesheets/staff/navigation.css
         - public/stylesheets/staff/tabbed_navigation.css
         - public/stylesheets/staff/forms.css
         - public/stylesheets/staff/page_styles.css
         - public/stylesheets/staff/pagination.css

