javascript_compressor: "closure"

javascripts:
    general:
        - public/javascripts/jquery.js
        - public/javascripts/rails.js
        - public/javascripts/application.js
 
stylesheets:
    public:
        - public/stylesheets/screen.css
    print:
        - public/stylesheets/print.css
    staff:
         - public/stylesheets/staff/main.css
         - public/stylesheets/staff/general.css
         - public/stylesheets/staff/navigation.css
         - public/stylesheets/staff/tabbed_navigation.css
         - public/stylesheets/staff/forms.css
         - public/stylesheets/staff/page_styles.css
         - public/stylesheets/staff/pagination.css

